# -----------------------------------------------------------------------------
#
#                             User Design
#
# -----------------------------------------------------------------------------

[[design]]
    name = "b1.f1"
    description = "Building 1, Floor 1"
    package = "netcad_demo_clabs1.b1_f1"

    [design.config]
        building = 1
        floor = 1

 [[design]]
    name = "b1.f2"
    description = "Building 1, Floor 2"
    package = "netcad_demo_clabs1.b1_f2"

    [design.config]
        building = 1
        floor = 2

[[design]]
    name = "b2.f9"
    description = "Building 2, Floor 9"
    package = "netcad_demo_clabs1.b1_f2"

    [design.config]
        building = 2
        floor = 9

# -----------------------------------------------------------------------------
#
#                                netcad plugins
#
# -----------------------------------------------------------------------------

[[netcad.plugins]]
    name = "ContainerLabs"
    package = "netcad_demo_clabs1.plugins.containerlabs"

# -----------------------------------------------------------------------------
#
#                                netcam plugins
#
# -----------------------------------------------------------------------------

[[netcam.plugins]]

    name = "Arista EOS"
    supports = ["eos"]
    package = "netcam_aioeos"

    [netcam.plugins.config]
        # the EOS credentials will be sourced from these enviornment variables.
        # so these need to be exported before use, or an error is reported.
        env.username = "NETWORK_USERNAME"
        env.password = "NETWORK_PASSWORD"

# -----------------------------------------------------------------------------
#
#                                origin plugins
#
# -----------------------------------------------------------------------------

[origin.netbox]
    url = "http://localhost:8000"
    token = "$NETBOX_TOKEN"
    package = "netcad.netbox:netbox"


[get]
    device-types = "netbox"

