# -----------------------------------------------------------------------------
#
#                             User Design
#
# -----------------------------------------------------------------------------

[[design]]
    name = "clab1"
    description = "ContainerLabs basic switching demo"
    package = "netcad_demo_clabs1"

# -----------------------------------------------------------------------------
#
#                                netcad plugins
#
# -----------------------------------------------------------------------------

[[netcad.plugins]]
    name = "ContainerLabs"
    package = "netcad_demo_clabs1.plugins.containerlabs"

# -----------------------------------------------------------------------------
#
#                                netcam plugins
#
# -----------------------------------------------------------------------------

[[netcam.plugins]]

    name = "Arista EOS"
    supports = ["eos"]
    package = "netcam_aioeos"

    [[netcam.plugins.config]]
        env.username = "NETWORK_USERNAME"
        env.password = "NETWORK_PASSWORD"

# -----------------------------------------------------------------------------
#
#                                origin plugins
#
# -----------------------------------------------------------------------------

[origin.netbox]
    url = "http://localhost:8000"
    token = "$NETBOX_TOKEN"
    package = "netcad.netbox:netbox"


[get]
    device-types = "netbox"

